version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:5.7
    environment: 
      - MYSQL_DATABASE=db-stocks
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root